"use client";

import React,{useMemo,useState} from "react";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {Upload,FileText,RefreshCw,Download} from "lucide-react";

type Row=Record<string,any>; type Snap={name:string;rows:Row[]};
const C={nmTotal:"No Mapping Notices",nmPending:"Pending EPIC - No Mapping",nmDisposed:"No Mapping Approved / Disposed",nmDocs:"Documents Uploaded by BLO - No Mapping",dTotal:"Anomaly Notices",dPending:"Pending EPIC - Discrepancy",dDisposed:"Discrepancy Approved / Disposed",dLetter:"BLO Letter Uploaded - Discrepancy"};
const num=(v:any)=>Number(v)||0; const pct=(a:number,b:number)=>b?Math.round(a/b*1000)/10:0;
function normal(rows:Row[]){return rows.filter(r=>/^\d+$/.test(String(r["PS NO."]))).map(r=>({...r,["PS NO."]:Number(r["PS NO."]),[C.nmTotal]:num(r[C.nmTotal]),[C.nmPending]:num(r[C.nmPending]),[C.nmDisposed]:num(r[C.nmDisposed]),[C.nmDocs]:num(r[C.nmDocs]),[C.dTotal]:num(r[C.dTotal]),[C.dPending]:num(r[C.dPending]),[C.dDisposed]:num(r[C.dDisposed]),[C.dLetter]:num(r[C.dLetter])}));}
async function load(f:File){const b=await f.arrayBuffer(),w=XLSX.read(b,{type:"array"}),s=w.SheetNames.includes("FINAL PS WISE REPORT")?"FINAL PS WISE REPORT":w.SheetNames[0];return {name:f.name,rows:normal(XLSX.utils.sheet_to_json<Row>(w.Sheets[s],{defval:""}))};}
function map(rows:Row[]){const m=new Map<number,Row>();rows.forEach(r=>m.set(r["PS NO."],r));return m;}
function sum(rows:Row[]){const o:any={};Object.values(C).forEach(c=>o[c]=rows.reduce((a,r)=>a+num(r[c]),0));return o;}
export default function Page(){
 const [s1,setS1]=useState<Snap|null>(null),[s2,setS2]=useState<Snap|null>(null),[q,setQ]=useState(""),[off,setOff]=useState("ALL");
 const base=s2?.rows||s1?.rows||[], prior=useMemo(()=>map(s1?.rows||[]),[s1]);
 const officers=[...new Set(base.map(r=>r["AERO / Ad.AERO"]).filter(Boolean))].sort();
 const rows=base.filter(r=>(off==="ALL"||r["AERO / Ad.AERO"]===off)&&((String(r["PS NO."]).includes(q))||String(r["BLO Name"]||"").toLowerCase().includes(q.toLowerCase())||String(r["BLO Supervisor"]||"").toLowerCase().includes(q.toLowerCase())||String(r["AERO / Ad.AERO"]||"").toLowerCase().includes(q.toLowerCase())));
 const t=sum(rows);
 const comp=rows.map(r=>{const p=prior.get(r["PS NO."]), d=num(r[C.nmDisposed])+num(r[C.dDisposed])-(num(p?.[C.nmDisposed])+num(p?.[C.dDisposed]));return {...r,nmp:pct(num(r[C.nmDisposed]),num(r[C.nmTotal])),dp:pct(num(r[C.dDisposed]),num(r[C.dTotal])),tp:pct(num(r[C.nmDisposed])+num(r[C.dDisposed]),num(r[C.nmTotal])+num(r[C.dTotal])),delta:d};});
 function choose(setter:any){return async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f)setter(await load(f));};}
 function pdf(kind:"PS"|"OFFICER"|"CONSOLIDATED"){const doc=new jsPDF("l","mm","a4");doc.setFontSize(16);doc.text("AC-34 MATIALA — "+kind+" NO MAPPING & DISCREPANCY REPORT",14,14);doc.setFontSize(9);doc.text("Generated: "+new Date().toLocaleString("en-IN"),14,20);autoTable(doc,{startY:25,head:[["PS","Officer","Supervisor","BLO","NM Total","NM Pending","NM Disposed","NM Docs","NM %","Disc Total","Disc Pending","Disc Disposed","BLO Letter","Disc %","Total %"]],body:comp.map(r=>[r["PS NO."],r["AERO / Ad.AERO"],r["BLO Supervisor"],r["BLO Name"],r[C.nmTotal],r[C.nmPending],r[C.nmDisposed],r[C.nmDocs],r.nmp+"%",r[C.dTotal],r[C.dPending],r[C.dDisposed],r[C.dLetter],r.dp+"%",r.tp+"%"]),styles:{fontSize:7,cellPadding:1.4},headStyles:{fontSize:7,fontStyle:"bold"}});doc.save(kind.toLowerCase()+"-report.pdf");}
 return <main><header><div><h1>AC-34 MATIALA</h1><p>No Mapping & Discrepancy Notice Dashboard</p></div><button className="reset" onClick={()=>{setS1(null);setS2(null)}}><RefreshCw size={16}/> Reset</button></header>
 <section className="uploads"><label className="upload"><Upload size={22}/><b>UPLOAD SNAPSHOT 1</b><span>{s1?.name||"Previous / baseline Excel"}</span><input type="file" accept=".xlsx,.xls" onChange={choose(setS1)}/></label><label className="upload latest"><Upload size={22}/><b>UPLOAD SNAPSHOT 2</b><span>{s2?.name||"Latest Excel"}</span><input type="file" accept=".xlsx,.xls" onChange={choose(setS2)}/></label></section>
 <section className="toolbar"><input placeholder="Search PS / BLO / Supervisor / Officer" value={q} onChange={e=>setQ(e.target.value)}/><select value={off} onChange={e=>setOff(e.target.value)}><option value="ALL">All Officers</option>{officers.map(x=><option key={x}>{x}</option>)}</select><div className="actions"><button onClick={()=>pdf("PS")}><Download size={15}/> PS PDF</button><button onClick={()=>pdf("OFFICER")}><FileText size={15}/> Officer PDF</button><button onClick={()=>pdf("CONSOLIDATED")}><FileText size={15}/> Consolidated PDF</button></div></section>
 <section className="cards"><Card t="NO MAPPING TOTAL" v={t[C.nmTotal]} s={(t[C.nmDisposed]||0)+" disposed · "+(t[C.nmPending]||0)+" pending"}/><Card t="NO MAPPING DOCUMENTS" v={t[C.nmDocs]} s={pct(t[C.nmDocs],t[C.nmTotal])+"% of notices"}/><Card t="DISCREPANCY TOTAL" v={t[C.dTotal]} s={(t[C.dDisposed]||0)+" disposed · "+(t[C.dPending]||0)+" pending"}/><Card t="BLO LETTERS" v={t[C.dLetter]} s={pct(t[C.dLetter],t[C.dTotal])+"% of discrepancy"}/><Card t="TOTAL DISPOSED" v={(t[C.nmDisposed]+t[C.dDisposed])} s={pct(t[C.nmDisposed]+t[C.dDisposed],t[C.nmTotal]+t[C.dTotal])+"% disposal"}/><Card t="NEW DISPOSALS" v={comp.reduce((a,r)=>a+r.delta,0)} s="vs Snapshot 1"/></section>
 <section className="panel"><div className="ph"><div><h2>PS-wise Report</h2><small>{rows.length} PS records {s1&&s2?"· snapshot comparison active":"· latest snapshot"}</small></div></div><div className="tablewrap"><table><thead><tr>{["PS","Officer","Supervisor","BLO","NM Total","NM Pending","NM Disposed","NM Docs","NM Dispose %","Disc Total","Disc Pending","Disc Disposed","BLO Letter","Disc Dispose %","Total Dispose %",...(s1&&s2?["Δ Disposed"]:[])].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{comp.map(r=><tr key={r["PS NO."]}><td>{r["PS NO."]}</td><td>{r["AERO / Ad.AERO"]}</td><td>{r["BLO Supervisor"]}</td><td>{r["BLO Name"]}</td><td>{r[C.nmTotal]}</td><td>{r[C.nmPending]}</td><td>{r[C.nmDisposed]}</td><td>{r[C.nmDocs]}</td><td className={r.nmp>=75?"good":r.nmp>=50?"warn":"bad"}>{r.nmp}%</td><td>{r[C.dTotal]}</td><td>{r[C.dPending]}</td><td>{r[C.dDisposed]}</td><td>{r[C.dLetter]}</td><td className={r.dp>=75?"good":r.dp>=50?"warn":"bad"}>{r.dp}%</td><td className={r.tp>=75?"good":r.tp>=50?"warn":"bad"}>{r.tp}%</td>{s1&&s2?<td className={r.delta>0?"up":""}>{r.delta>0?"+":""}{r.delta}</td>:null}</tr>)}</tbody></table></div></section>
 <style jsx global>{`body{margin:0;background:#f3f6f9;color:#172033;font-family:Arial,sans-serif}main{max-width:1800px;margin:auto;padding:24px}header,.ph{display:flex;justify-content:space-between;align-items:center}h1{margin:0;font-size:28px}p,small{color:#748094}.uploads{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:18px 0}.upload,.toolbar,.panel,.card{background:#fff;border-radius:16px;box-shadow:0 4px 18px rgba(20,33,61,.06)}.upload{position:relative;padding:22px;display:flex;flex-direction:column;gap:6px;border:1px dashed #b8c1ce}.latest{border-color:#6678ee;background:#fafbff}.upload input{position:absolute;inset:0;opacity:0;cursor:pointer}.toolbar{padding:12px;display:flex;gap:10px;align-items:center;margin-bottom:16px}.toolbar input{flex:1;padding:11px;border:1px solid #d6dce6;border-radius:10px}.toolbar select{padding:11px;border:1px solid #d6dce6;border-radius:10px;background:#fff}.actions{display:flex;gap:8px}.actions button,.reset{display:flex;align-items:center;gap:6px;border:0;border-radius:10px;padding:10px 12px;background:#172033;color:white;font-weight:700;cursor:pointer}.reset{background:white;color:#445067;border:1px solid #d6dce6}.cards{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin-bottom:16px}.card{padding:16px}.muted{font-size:11px;color:#778398;font-weight:800}.big{font-size:27px;font-weight:900;margin:7px 0}.panel{overflow:hidden}.ph{padding:16px 18px}.tablewrap{overflow:auto;max-height:68vh}table{width:100%;min-width:1500px;border-collapse:collapse}th,td{padding:9px 8px;border-bottom:1px solid #e8edf3;font-size:12px;text-align:center;white-space:nowrap}th{position:sticky;top:0;background:#172033;color:white;font-size:10px;text-transform:uppercase}td:nth-child(2),td:nth-child(3),td:nth-child(4){text-align:left}.good{background:#d9f2df;font-weight:900}.warn{background:#fff0c6;font-weight:900}.bad{background:#ffe0e3;font-weight:900}.up{color:#16723b;font-weight:900}@media(max-width:1200px){.cards{grid-template-columns:repeat(3,1fr)}.uploads{grid-template-columns:1fr}.toolbar{flex-wrap:wrap}}`}</style></main>;
}
function Card(p:{t:string,v:number,s:string}){return <div className="card"><div className="muted">{p.t}</div><div className="big">{p.v.toLocaleString()}</div><div>{p.s}</div></div>}
